
download:
	wget -r  https://www.swissbiopics.org/
	
	mkdir -p {js,css,images}
	
	cp www.swissbiopics.org/prime/cache1/* images/.
	cp www.swissbiopics.org/resources/css/* css/.
	cp www.swissbiopics.org/resources/js/* js/.


clean:
	rm -rf www.swissbiopics.org
	